INSERT INTO `em_regioni` (`codiceRegione`, `descrizioneRegione`) VALUES(1, 'Abruzzo');
INSERT INTO `em_regioni` (`codiceRegione`, `descrizioneRegione`) VALUES(2, 'Basilicata');
INSERT INTO `em_regioni` (`codiceRegione`, `descrizioneRegione`) VALUES(3, 'Calabria');
INSERT INTO `em_regioni` (`codiceRegione`, `descrizioneRegione`) VALUES(4, 'Campania');
INSERT INTO `em_regioni` (`codiceRegione`, `descrizioneRegione`) VALUES(5, 'Emilia-Romagna');
INSERT INTO `em_regioni` (`codiceRegione`, `descrizioneRegione`) VALUES(6, 'Friuli-Venezia Giulia');
INSERT INTO `em_regioni` (`codiceRegione`, `descrizioneRegione`) VALUES(7, 'Lazio');
INSERT INTO `em_regioni` (`codiceRegione`, `descrizioneRegione`) VALUES(8, 'Liguria');
INSERT INTO `em_regioni` (`codiceRegione`, `descrizioneRegione`) VALUES(9, 'Lombardia');
INSERT INTO `em_regioni` (`codiceRegione`, `descrizioneRegione`) VALUES(10, 'Marche');
INSERT INTO `em_regioni` (`codiceRegione`, `descrizioneRegione`) VALUES(11, 'Molise');
INSERT INTO `em_regioni` (`codiceRegione`, `descrizioneRegione`) VALUES(12, 'Piemonte');
INSERT INTO `em_regioni` (`codiceRegione`, `descrizioneRegione`) VALUES(13, 'Puglia');
INSERT INTO `em_regioni` (`codiceRegione`, `descrizioneRegione`) VALUES(14, 'Sardegna');
INSERT INTO `em_regioni` (`codiceRegione`, `descrizioneRegione`) VALUES(15, 'Sicilia');
INSERT INTO `em_regioni` (`codiceRegione`, `descrizioneRegione`) VALUES(16, 'Toscana');
INSERT INTO `em_regioni` (`codiceRegione`, `descrizioneRegione`) VALUES(17, 'Trentino-Alto Adige');
INSERT INTO `em_regioni` (`codiceRegione`, `descrizioneRegione`) VALUES(18, 'Umbria');
INSERT INTO `em_regioni` (`codiceRegione`, `descrizioneRegione`) VALUES(19, 'Valle d\'Aosta');
INSERT INTO `em_regioni` (`codiceRegione`, `descrizioneRegione`) VALUES(20, 'Veneto');